import type { Property } from "./types"

// Updated data with new commercial projects - showing only 3 residential and 7 commercial properties
const properties: Property[] = [
  // RESIDENTIAL PROPERTIES (Only 3)
  {
    id: "1",
    name: "Aster Neo",
    category: "residential",
    type: "Apartment",
    bhk: 2,
    price: "77",
    priceUnit: "Lakhs",
    priceDescription: "All Including",
    image: "/placeholder.svg?height=300&width=400",
    heroImage: "/placeholder.svg?height=500&width=800",
    location: "Adani Shantigram",
    possession: "2025",
    size: "1205",
    superBuiltUpArea: "690",
    companyLogo: "/placeholder.svg?height=60&width=120",
    description:
      "2 BHK apartments in Adani Shantigram offering modern living with premium amenities and excellent connectivity.",
    amenities: ["Gym", "Swimming Pool", "Garden", "Clubhouse", "Children's Play Area", "Senior Citizen Sit-out"],
    gallery: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    rera: "PR/GJ/AHMEDABAD/AHMEDABAD CITY/AUDA/RAA07338/140820",
  },
  {
    id: "2",
    name: "Greenview",
    category: "residential",
    type: "Apartment",
    bhk: 3,
    price: "1.63",
    priceUnit: "Cr",
    priceDescription: "All Including",
    image: "/placeholder.svg?height=300&width=400",
    heroImage: "/placeholder.svg?height=500&width=800",
    location: "Adani Shantigram",
    possession: "2025",
    size: "2335",
    superBuiltUpArea: "1284",
    companyLogo: "/placeholder.svg?height=60&width=120",
    description: "3 BHK+WFH apartments in Adani Shantigram offering modern living with work from home facilities.",
    amenities: ["Gym", "Swimming Pool", "Garden", "Clubhouse", "Children's Play Area", "Senior Citizen Sit-out"],
    gallery: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    rera: "PR/GJ/AHMEDABAD/AHMEDABAD CITY/AUDA/RAA09534/241221",
  },
  {
    id: "3",
    name: "North Park",
    category: "residential",
    type: "Villa",
    bhk: 4,
    price: "Price On Request",
    priceUnit: "",
    priceDescription: "All Including",
    image: "/placeholder.svg?height=300&width=400",
    location: "Adani Shantigram",
    possession: "",
    size: "550",
    superBuiltUpArea: "saleable area",
    companyLogo: "/placeholder.svg?height=60&width=120",
    description:
      "4 BHK Villas in Adani Shantigram offering exclusive living with private spaces and premium amenities.",
    amenities: ["Private Garden", "Swimming Pool", "Clubhouse", "Children's Play Area", "Senior Citizen Sit-out"],
    gallery: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    rera: "PR/GJ/AHMEDABAD/AHMEDABAD CITY/AUDA/RAA01824/010318",
  },

  // UPDATED COMMERCIAL PROPERTIES (7 Projects with real images)
  {
    id: "c1",
    name: "Shilp Centrica",
    category: "commercial",
    type: "Office Spaces / Showrooms",
    developer: "Shilp Group",
    price: "₹1.81 Cr - ₹6.10 Cr",
    priceUnit: "",
    priceDescription: "Office & Showroom Options Available",
    officeSize: "1500 Sqft",
    showroomSize: "2200 – 3509 Sqft",
    officePrice: "₹1.81 Cr",
    showroomPrice: "₹5.94 Cr – ₹6.10 Cr",
    image: "/images/commercial/shilp-centrica.jpg",
    heroImage: "/images/commercial/shilp-centrica.jpg",
    location: "Adani Shantigram",
    possession: "Dec 2027",
    size: "1500 - 3509",
    superBuiltUpArea: "sqft (Office & Showroom)",
    floorDetails: "Multiple Floors Available",
    parkingSpaces: 2,
    suitableFor: ["Corporate Office", "Showroom", "Retail Space", "Business Center"],
    companyLogo: "/placeholder.svg?height=60&width=120",
    description:
      "Shilp Centrica by Shilp Group offers premium office spaces and showrooms with modern amenities and strategic location in Adani Shantigram. Perfect for businesses looking for professional workspace solutions with flexible sizing options.",
    amenities: ["High Speed Internet", "24/7 Security", "Power Backup", "Parking", "Elevator", "Reception Area"],
    gallery: [
      "/images/commercial/shilp-centrica.jpg",
      "/images/commercial/shilp-centrica-gallery-1.jpg",
      "/images/commercial/shilp-centrica-gallery-2.jpg",
      "/images/commercial/shilp-centrica-gallery-3.jpg",
      "/images/commercial/shilp-centrica-gallery-4.jpg",
      "/images/commercial/shilp-centrica-gallery-5.jpg",
    ],
    rera: "PR/GJ/GANDHINAGAR/GANDHINAGAR/Others/CAA12608/081123",
  },
  {
    id: "c2",
    name: "Shivalik Curv",
    category: "commercial",
    type: "Office Spaces",
    developer: "Shivalik Group",
    price: "₹2.20 Cr",
    priceUnit: "",
    priceDescription: "Premium Office Spaces",
    officeSize: "1875 Sqft",
    officePrice: "₹2.20 Cr",
    image: "/images/commercial/shivalik-curv.jpg",
    heroImage: "/images/commercial/shivalik-curv.jpg",
    location: "Adani Shantigram",
    possession: "Dec 2029",
    size: "1875",
    superBuiltUpArea: "sqft",
    floorDetails: "Premium Floors Available",
    parkingSpaces: 2,
    suitableFor: ["Corporate Office", "IT Company", "Consultancy", "Financial Services"],
    companyLogo: "/placeholder.svg?height=60&width=120",
    description:
      "Shivalik Curv by Shivalik Group presents contemporary office spaces designed for modern businesses. Features state-of-the-art infrastructure and premium amenities for professional excellence.",
    amenities: ["High Speed Internet", "24/7 Security", "Power Backup", "Parking", "Conference Rooms", "Cafeteria"],
    gallery: [
      "/images/commercial/shivalik-curv.jpg",
      "/images/commercial/shivalik-curv-gallery-1.jpg",
      "/images/commercial/shivalik-curv-gallery-2.jpg",
      "/images/commercial/shivalik-curv-gallery-3.jpg",
      "/images/commercial/shivalik-curv-gallery-4.jpg",
      "/images/commercial/shivalik-curv-gallery-5.jpg",
    ],
    rera: "PR/GANDHINAGAR/GANDHINAGAR/Others/CAA12514/211023",
  },
  {
    id: "c3",
    name: "Kavyaratna Narmada",
    category: "commercial",
    type: "Office Spaces / Showrooms",
    developer: "Kaavyaratna and Ekarth Group",
    price: "₹1.80 Cr - ₹13 Cr",
    priceUnit: "",
    priceDescription: "Office & Showroom Options Available",
    officeSize: "2000 – 4000 Sqft",
    showroomSize: "3500 – 4700 Sqft",
    officePrice: "₹1.80 Cr – ₹3.60 Cr",
    showroomPrice: "₹9.45 Cr – ₹13 Cr",
    image: "/images/commercial/kavyaratna-narmada.jpg",
    heroImage: "/images/commercial/kavyaratna-narmada.jpg",
    location: "Adani Shantigram",
    possession: "Dec 2026",
    size: "2000 - 4700",
    superBuiltUpArea: "sqft (Office: 2000-4000, Showroom: 3500-4700)",
    floorDetails: "Ground to Upper Floors",
    parkingSpaces: 3,
    suitableFor: ["Corporate Office", "Showroom", "Retail Store", "Business Hub"],
    companyLogo: "/placeholder.svg?height=60&width=120",
    description:
      "Kavyaratna Narmada by Kaavyaratna and Ekarth Group offers versatile commercial spaces including office spaces and showrooms. Strategically located with excellent connectivity and modern infrastructure.",
    amenities: ["High Speed Internet", "24/7 Security", "Power Backup", "Parking", "Loading Area", "Reception"],
    gallery: [
      "/images/commercial/kavyaratna-narmada.jpg",
      "/images/commercial/kavyaratna-narmada-gallery-1.jpg",
      "/images/commercial/kavyaratna-narmada-gallery-2.jpg",
      "/images/commercial/kavyaratna-narmada-gallery-3.jpg",
      "/images/commercial/kavyaratna-narmada-gallery-4.jpg",
    ],
    rera: "PR/GJ/GANDHINAGAR/GANDHINAGAR/GIFT Urban Development Authority/CN373AA10273/161123",
  },
  {
    id: "c4",
    name: "Nakshatra Regalia",
    category: "commercial",
    type: "Office Spaces / Showrooms",
    developer: "Nakshatra Group",
    price: "₹2.97 Cr - ₹4.50 Cr",
    priceUnit: "",
    priceDescription: "Office & Showroom Options Available",
    officeSize: "3500 Sqft",
    showroomSize: "2400 Sqft",
    officePrice: "₹2.97 Cr",
    showroomPrice: "₹4.50 Cr",
    image: "/images/commercial/nakshatra-regalia.jpg",
    heroImage: "/images/commercial/nakshatra-regalia.jpg",
    location: "Adani Shantigram",
    possession: "Dec 2028",
    size: "2400 - 3500",
    superBuiltUpArea: "sqft",
    floorDetails: "Premium Commercial Floors",
    parkingSpaces: 4,
    suitableFor: ["Large Corporate Office", "Premium Showroom", "Business Center", "Headquarters"],
    companyLogo: "/placeholder.svg?height=60&width=120",
    description:
      "Nakshatra Regalia by Nakshatra Group offers spacious premium office spaces and showrooms ideal for large corporations and established businesses. Features world-class amenities and professional infrastructure.",
    amenities: [
      "High Speed Internet",
      "24/7 Security",
      "Power Backup",
      "Parking",
      "Conference Rooms",
      "Executive Lounge",
    ],
    gallery: [
      "/images/commercial/nakshatra-regalia.jpg",
      "/images/commercial/nakshatra-regalia-gallery-1.jpg",
      "/images/commercial/nakshatra-regalia-gallery-2.jpg",
      "/images/commercial/nakshatra-regalia-gallery-3.jpg",
      "/images/commercial/nakshatra-regalia-gallery-4.jpg",
      "/images/commercial/nakshatra-regalia-gallery-5.jpg",
    ],
    rera: "PR/GJ/GANDHINAGAR/GANDHINAGAR/Others/CAA10420/110722",
  },
  {
    id: "c5",
    name: "Nakshatra Regalia 2",
    category: "commercial",
    type: "Office Spaces / Showrooms",
    developer: "Nakshatra Group",
    price: "₹76 Lac - ₹11.25 Cr",
    priceUnit: "",
    priceDescription: "Flexible Office & Showroom Options",
    officeSize: "900 – 1300 Sqft",
    showroomSize: "1300 – 5000 Sqft",
    officePrice: "₹76 Lac – ₹1.10 Cr",
    showroomPrice: "₹2.93 Cr – ₹11.25 Cr",
    image: "/images/commercial/nakshatra-regalia-2.jpg",
    heroImage: "/images/commercial/nakshatra-regalia-2.jpg",
    location: "Adani Shantigram",
    possession: "Dec 2027",
    size: "900 - 5000",
    superBuiltUpArea: "sqft (Office: 900-1300, Showroom: 1300-5000)",
    floorDetails: "Multiple Floor Options",
    parkingSpaces: 3,
    suitableFor: ["Small to Large Office", "Showroom", "Retail Space", "Business Center"],
    companyLogo: "/placeholder.svg?height=60&width=120",
    description:
      "Nakshatra Regalia 2 by Nakshatra Group offers flexible commercial spaces ranging from compact offices to large showrooms. Perfect for businesses of all sizes with premium amenities and strategic location.",
    amenities: [
      "High Speed Internet",
      "24/7 Security",
      "Power Backup",
      "Parking",
      "Flexible Layouts",
      "Modern Infrastructure",
    ],
    gallery: [
      "/images/commercial/nakshatra-regalia-2.jpg",
      "/images/commercial/nakshatra-regalia-2-gallery-1.jpg",
      "/images/commercial/nakshatra-regalia-2-gallery-2.jpg",
    ],
    rera: "PR/GJ/GANDHINAGAR/GANDHINAGAR/GIFT Urban Development Authority/CAA14350/281024/311230",
  },
  {
    id: "c6",
    name: "The Identity",
    category: "commercial",
    type: "Office Spaces / Showrooms",
    developer: "Dobariya, Rashmi & Sangini Group",
    price: "₹68 Lac - ₹6 Cr",
    priceUnit: "",
    priceDescription: "Office & Showroom Options Available",
    officeSize: "801 – 1500 Sqft",
    showroomSize: "2800 – 3000 Sqft",
    officePrice: "₹68 Lac – ₹1.28 Cr",
    showroomPrice: "₹2.80 Cr – ₹6 Cr",
    image: "/images/commercial/the-identity.jpg",
    heroImage: "/images/commercial/the-identity.jpg",
    location: "Adani Shantigram",
    possession: "Dec 2027",
    size: "801 - 3000",
    superBuiltUpArea: "sqft (Office: 801-1500, Showroom: 2800-3000)",
    floorDetails: "Ground to Premium Floors",
    parkingSpaces: 2,
    suitableFor: ["Corporate Office", "Showroom", "Boutique Store", "Professional Services"],
    companyLogo: "/placeholder.svg?height=60&width=120",
    description:
      "The Identity by Dobariya, Rashmi & Sangini Group offers distinctive commercial spaces with unique architectural design. Ideal for businesses seeking a premium identity and professional presence.",
    amenities: [
      "High Speed Internet",
      "24/7 Security",
      "Power Backup",
      "Parking",
      "Modern Design",
      "Professional Lobby",
    ],
    gallery: [
      "/images/commercial/the-identity.jpg",
      "/images/commercial/the-identity-gallery-1.jpg",
      "/images/commercial/the-identity-gallery-2.jpg",
      "/images/commercial/the-identity-gallery-3.jpg",
      "/images/commercial/the-identity-gallery-4.jpg",
    ],
    rera: "PR/GJ/GANDHINAGAR/GANDHINAGAR/GIFT Urban Development Authority/CAA14504/121224/301230",
  },
  {
    id: "c7",
    name: "Yogi Siban",
    category: "commercial",
    type: "Showrooms",
    developer: "Yogi & Akshar & Globe & United Buildcon",
    price: "₹4.67 Cr - ₹6.05 Cr",
    priceUnit: "",
    priceDescription: "Premium Showroom Spaces",
    showroomSize: "1700 – 5500 Sqft",
    showroomPrice: "₹4.67 Cr – ₹6.05 Cr",
    image: "/images/commercial/yogi-siban.jpg",
    heroImage: "/images/commercial/yogi-siban.jpg",
    location: "Adani Shantigram",
    possession: "Dec 2030",
    size: "1700 - 5500",
    superBuiltUpArea: "sqft",
    floorDetails: "Ground Floor with High Visibility",
    parkingSpaces: 4,
    suitableFor: ["Large Showroom", "Retail Store", "Brand Outlet", "Display Center"],
    companyLogo: "/placeholder.svg?height=60&width=120",
    description:
      "Yogi Siban by Yogi & Akshar & Globe & United Buildcon offers premium showroom spaces with excellent visibility and accessibility. Perfect for retail businesses, brand outlets, and large display centers with flexible sizing options.",
    amenities: [
      "High Visibility",
      "24/7 Security",
      "Power Backup",
      "Ample Parking",
      "Loading Area",
      "Customer Facilities",
    ],
    gallery: [
      "/images/commercial/yogi-siban.jpg",
      "/images/commercial/yogi-siban-gallery-1.jpg",
      "/images/commercial/yogi-siban-gallery-2.jpg",
      "/images/commercial/yogi-siban-gallery-3.jpg",
      "/images/commercial/yogi-siban-gallery-4.jpg",
    ],
    rera: "PR/GJ/GANDHINAGAR/GANDHINAGAR/GIFT Urban Development Authority/MAA14625/311224/311230",
  },
]

export async function getPropertiesByCategory(category: "residential" | "commercial"): Promise<Property[]> {
  try {
    await new Promise((resolve) => setTimeout(resolve, 100))
    return properties.filter((property) => property.category === category)
  } catch (error) {
    console.error("Error fetching properties by category:", error)
    throw new Error("Failed to fetch properties by category")
  }
}

export async function getProperties(): Promise<Property[]> {
  try {
    await new Promise((resolve) => setTimeout(resolve, 100))
    return properties
  } catch (error) {
    console.error("Error fetching properties:", error)
    throw new Error("Failed to fetch properties")
  }
}

export async function getPropertyById(id: string): Promise<Property | null> {
  try {
    await new Promise((resolve) => setTimeout(resolve, 100))
    const property = properties.find((property) => property.id === id)
    return property || null
  } catch (error) {
    console.error("Error fetching property:", error)
    throw new Error("Failed to fetch property")
  }
}
