import type { Property } from "./types"

// Updated data with new commercial projects - showing only 3 residential and 7 commercial properties
const properties: Property[] = [
  // RESIDENTIAL PROPERTIES (Only 3)
  {
    id: "1",
    name: "Nila Vida",
    category: "residential",
    type: "Apartment",
    bhk: 3, // 1 to 3 BHK, using max for display
    price: "1.11 - 2.47",
    priceUnit: "Cr",
    priceDescription: "1 to 3 BHK",
    image: "/images/residential/r1.jpg",
    heroImage: "/images/residential/r1.jpg",
    location: "Ahmedabad",
    possession: "Dec 2026",
    size: "529 - 1180",
    superBuiltUpArea: "sqft",
    companyLogo: "/placeholder.svg?height=60&width=120",
    description: "1 to 3 BHK apartments in Adani Shantigram. Modern living, premium amenities, and excellent connectivity.",
    amenities: ["Gym", "Swimming Pool", "Garden", "Clubhouse", "Children's Play Area", "Senior Citizen Sit-out"],
    gallery: [
      "/images/residential/r1-1.jpg",
      "/images/residential/r1-3.jpg",
      "/images/residential/r1-5.jpg"
    ],
    rera: "PR/GJ/GANDHINAGAR/GANDHINAGAR/GIFT Urban Development Authority/RN209AA10109/011022",
  },
  {
    id: "2",
    name: "Sangath IPL Smart Life",
    category: "residential",
    type: "Apartment",
    bhk: 2,
    price: "1.25",
    priceUnit: "Cr",
    priceDescription: "2 BHK",
    image: "/images/residential/r2.jpg",
    heroImage: "/images/residential/r2.jpg",
    location: "Adani Shantigram",
    possession: "Ready Possession",
    size: "1410",
    superBuiltUpArea: "sqft",
    companyLogo: "/placeholder.svg?height=60&width=120",
    description: "2 BHK apartments in Adani Shantigram. Ready to move in, with all modern amenities.",
    amenities: ["Gym", "Swimming Pool", "Garden", "Clubhouse", "Children's Play Area", "Senior Citizen Sit-out"],
    gallery: [
      "/images/residential/r2-1.jpg",
      "/images/residential/r2-3.jpg",
      "/images/residential/r2-4.jpg",
      "/images/residential/r2-5.jpg"
    ],
    rera: "PR/GJ/GANDHINAGAR/GANDHINAGAR/OTHERS/MAA07381/250820",
  },
  {
    id: "3",
    name: "Reva by Kaavyaratna",
    category: "residential",
    type: "Apartment",
    bhk: 4, // 2 BHK to 4.5 BHK, using max for display
    price: "1.17 - 3.64",
    priceUnit: "Cr",
    priceDescription: "2 BHK to 4.5 BHK",
    image: "/images/residential/r3.jpg",
    heroImage: "/images/residential/r3.jpg",
    location: "Adani Shantigram",
    possession: "Dec 2026",
    size: "1177 - 3868",
    superBuiltUpArea: "sqft",
    companyLogo: "/placeholder.svg?height=60&width=120",
    description: "2 BHK to 4.5 BHK apartments in Adani Shantigram. Spacious homes with luxury amenities.",
    amenities: ["Gym", "Swimming Pool", "Garden", "Clubhouse", "Children's Play Area", "Senior Citizen Sit-out"],
    gallery: [
      "/images/residential/r3-1.jpg",
      "/images/residential/r3-2.jpg",
      "/images/residential/r3-3.jpg",
      "/images/residential/r3-4.jpg",
      "/images/residential/r3-5.jpg"
    ],
    rera: "PR/GJ/GANDHINAGAR/GANDHINAGAR/GIFT Urban Development Authority/MN140AA10040/300722",
  },
  {
    id: "4",
    name: "Savvy Marina",
    category: "residential",
    type: "Apartment",
    bhk: 4, // 3 BHK to 4 BHK, using max for display
    price: "1.68 - 3.36",
    priceUnit: "Cr",
    priceDescription: "3 BHK to 4 BHK",
    image: "/images/residential/r4.jpg",
    heroImage: "/images/residential/r4.jpg",
    location: "Adani Shantigram",
    possession: "Dec 2026",
    size: "2030 - 4420",
    superBuiltUpArea: "sqft",
    companyLogo: "/placeholder.svg?height=60&width=120",
    description: "3 BHK to 4 BHK apartments in Adani Shantigram. Premium living with world-class amenities.",
    amenities: ["Gym", "Swimming Pool", "Garden", "Clubhouse", "Children's Play Area", "Senior Citizen Sit-out"],
    gallery: [
      "/images/residential/r4-1.jpg",
      "/images/residential/r4-2.jpg",
      "/images/residential/r4-3.jpg",
      "/images/residential/r4-4.jpg",
      "/images/residential/r4-5.jpg"
    ],
    rera: "PR/GJ/GANDHINAGAR/GANDHINAGAR/OTHERS/MAA11100/301222",
  },
  {
    id: "5",
    name: "Sobha Elysia",
    category: "residential",
    type: "Apartment",
    bhk: 4, // 3 BHK to 4 BHK, using max for display
    price: "2.48 - 4.94",
    priceUnit: "Cr",
    priceDescription: "3 BHK to 4 BHK",
    image: "/images/residential/r5.jpg",
    heroImage: "/images/residential/r5.jpg",
    location: "Adani Shantigram",
    possession: "Dec 2030",
    size: "1817 - 3462",
    superBuiltUpArea: "sqft",
    companyLogo: "/placeholder.svg?height=60&width=120",
    description: "3 BHK to 4 BHK apartments in Adani Shantigram. Luxury homes with future-ready amenities.",
    amenities: ["Gym", "Swimming Pool", "Garden", "Clubhouse", "Children's Play Area", "Senior Citizen Sit-out"],
    gallery: [
      "/images/residential/r5-1.jpg",
      "/images/residential/r5-2.jpg",
      "/images/residential/r5-3.jpg",
      "/images/residential/r5-4.jpg",
      "/images/residential/r5-5.jpg",
      "/images/residential/r5-6.jpg",
      "/images/residential/r5-7.jpg"
    ],
    rera: "PR/GJ/GANDHINAGAR/GANDHINAGAR/GIFT Urban Development Authority/RAA13206/300324/311230",
  },

  // UPDATED COMMERCIAL PROPERTIES (7 Projects with real images)
  {
    id: "c1",
    name: "Shilp Centrica",
    category: "commercial",
    type: "Office Spaces / Showrooms",
    developer: "Shilp Group",
    price: "₹1.81 Cr - ₹6.10 Cr",
    priceUnit: "",
    priceDescription: "Office & Showroom Options Available",
    officeSize: "1500 Sqft",
    showroomSize: "2200 – 3509 Sqft",
    officePrice: "₹1.81 Cr",
    showroomPrice: "₹5.94 Cr – ₹6.10 Cr",
    image: "/images/commercial/shilp-centrica.jpg",
    heroImage: "/images/commercial/shilp-centrica.jpg",
    location: "Adani Shantigram",
    possession: "Dec 2027",
    size: "1500 - 3509",
    superBuiltUpArea: "sqft (Office & Showroom)",
    floorDetails: "Multiple Floors Available",
    parkingSpaces: 2,
    suitableFor: ["Corporate Office", "Showroom", "Retail Space", "Business Center"],
    companyLogo: "/placeholder.svg?height=60&width=120",
    description:
      "Shilp Centrica by Shilp Group offers premium office spaces and showrooms with modern amenities and strategic location in Adani Shantigram. Perfect for businesses looking for professional workspace solutions with flexible sizing options.",
    amenities: ["High Speed Internet", "24/7 Security", "Power Backup", "Parking", "Elevator", "Reception Area"],
    gallery: [
      "/images/commercial/shilp-centrica.jpg",
      "/images/commercial/shilp-centrica-gallery-1.jpg",
      "/images/commercial/shilp-centrica-gallery-2.jpg",
      "/images/commercial/shilp-centrica-gallery-3.jpg",
      "/images/commercial/shilp-centrica-gallery-4.jpg",
      "/images/commercial/shilp-centrica-gallery-5.jpg",
    ],
    rera: "PR/GJ/GANDHINAGAR/GANDHINAGAR/Others/CAA12608/081123",
  },
  {
    id: "c2",
    name: "Shivalik Curv",
    category: "commercial",
    type: "Office Spaces",
    developer: "Shivalik Group",
    price: "₹2.20 Cr",
    priceUnit: "",
    priceDescription: "Premium Office Spaces",
    officeSize: "1875 Sqft",
    officePrice: "₹2.20 Cr",
    image: "/images/commercial/shivalik-curv.jpg",
    heroImage: "/images/commercial/shivalik-curv.jpg",
    location: "Adani Shantigram",
    possession: "Dec 2029",
    size: "1875",
    superBuiltUpArea: "sqft",
    floorDetails: "Premium Floors Available",
    parkingSpaces: 2,
    suitableFor: ["Corporate Office", "IT Company", "Consultancy", "Financial Services"],
    companyLogo: "/placeholder.svg?height=60&width=120",
    description:
      "Shivalik Curv by Shivalik Group presents contemporary office spaces designed for modern businesses. Features state-of-the-art infrastructure and premium amenities for professional excellence.",
    amenities: ["High Speed Internet", "24/7 Security", "Power Backup", "Parking", "Conference Rooms", "Cafeteria"],
    gallery: [
      "/images/commercial/shivalik-curv.jpg",
      "/images/commercial/shivalik-curv-gallery-1.jpg",
      "/images/commercial/shivalik-curv-gallery-2.jpg",
      "/images/commercial/shivalik-curv-gallery-3.jpg",
      "/images/commercial/shivalik-curv-gallery-4.jpg",
      "/images/commercial/shivalik-curv-gallery-5.jpg",
    ],
    rera: "PR/GANDHINAGAR/GANDHINAGAR/Others/CAA12514/211023",
  },
  {
    id: "c3",
    name: "Kavyaratna Narmada",
    category: "commercial",
    type: "Office Spaces / Showrooms",
    developer: "Kaavyaratna and Ekarth Group",
    price: "₹1.80 Cr - ₹13 Cr",
    priceUnit: "",
    priceDescription: "Office & Showroom Options Available",
    officeSize: "2000 – 4000 Sqft",
    showroomSize: "3500 – 4700 Sqft",
    officePrice: "₹1.80 Cr – ₹3.60 Cr",
    showroomPrice: "₹9.45 Cr – ₹13 Cr",
    image: "/images/commercial/kavyaratna-narmada.jpg",
    heroImage: "/images/commercial/kavyaratna-narmada.jpg",
    location: "Adani Shantigram",
    possession: "Dec 2026",
    size: "2000 - 4700",
    superBuiltUpArea: "sqft (Office: 2000-4000, Showroom: 3500-4700)",
    floorDetails: "Ground to Upper Floors",
    parkingSpaces: 3,
    suitableFor: ["Corporate Office", "Showroom", "Retail Store", "Business Hub"],
    companyLogo: "/placeholder.svg?height=60&width=120",
    description:
      "Kavyaratna Narmada by Kaavyaratna and Ekarth Group offers versatile commercial spaces including office spaces and showrooms. Strategically located with excellent connectivity and modern infrastructure.",
    amenities: ["High Speed Internet", "24/7 Security", "Power Backup", "Parking", "Loading Area", "Reception"],
    gallery: [
      "/images/commercial/kavyaratna-narmada.jpg",
      "/images/commercial/kavyaratna-narmada-gallery-1.jpg",
      "/images/commercial/kavyaratna-narmada-gallery-2.jpg",
      "/images/commercial/kavyaratna-narmada-gallery-3.jpg",
      "/images/commercial/kavyaratna-narmada-gallery-4.jpg",
    ],
    rera: "PR/GJ/GANDHINAGAR/GANDHINAGAR/GIFT Urban Development Authority/CN373AA10273/161123",
  },
  {
    id: "c4",
    name: "Nakshatra Regalia",
    category: "commercial",
    type: "Office Spaces / Showrooms",
    developer: "Nakshatra Group",
    price: "₹2.97 Cr - ₹4.50 Cr",
    priceUnit: "",
    priceDescription: "Office & Showroom Options Available",
    officeSize: "3500 Sqft",
    showroomSize: "2400 Sqft",
    officePrice: "₹2.97 Cr",
    showroomPrice: "₹4.50 Cr",
    image: "/images/commercial/nakshatra-regalia.jpg",
    heroImage: "/images/commercial/nakshatra-regalia.jpg",
    location: "Adani Shantigram",
    possession: "Dec 2028",
    size: "2400 - 3500",
    superBuiltUpArea: "sqft",
    floorDetails: "Premium Commercial Floors",
    parkingSpaces: 4,
    suitableFor: ["Large Corporate Office", "Premium Showroom", "Business Center", "Headquarters"],
    companyLogo: "/placeholder.svg?height=60&width=120",
    description:
      "Nakshatra Regalia by Nakshatra Group offers spacious premium office spaces and showrooms ideal for large corporations and established businesses. Features world-class amenities and professional infrastructure.",
    amenities: [
      "High Speed Internet",
      "24/7 Security",
      "Power Backup",
      "Parking",
      "Conference Rooms",
      "Executive Lounge",
    ],
    gallery: [
      "/images/commercial/nakshatra-regalia.jpg",
      "/images/commercial/nakshatra-regalia-gallery-1.jpg",
      "/images/commercial/nakshatra-regalia-gallery-2.jpg",
      "/images/commercial/nakshatra-regalia-gallery-3.jpg",
      "/images/commercial/nakshatra-regalia-gallery-4.jpg",
      "/images/commercial/nakshatra-regalia-gallery-5.jpg",
    ],
    rera: "PR/GJ/GANDHINAGAR/GANDHINAGAR/Others/CAA10420/110722",
  },
  {
    id: "c5",
    name: "Nakshatra Regalia 2",
    category: "commercial",
    type: "Office Spaces / Showrooms",
    developer: "Nakshatra Group",
    price: "₹76 Lac - ₹11.25 Cr",
    priceUnit: "",
    priceDescription: "Flexible Office & Showroom Options",
    officeSize: "900 – 1300 Sqft",
    showroomSize: "1300 – 5000 Sqft",
    officePrice: "₹76 Lac – ₹1.10 Cr",
    showroomPrice: "₹2.93 Cr – ₹11.25 Cr",
    image: "/images/commercial/nakshatra-regalia-2.jpg",
    heroImage: "/images/commercial/nakshatra-regalia-2.jpg",
    location: "Adani Shantigram",
    possession: "Dec 2027",
    size: "900 - 5000",
    superBuiltUpArea: "sqft (Office: 900-1300, Showroom: 1300-5000)",
    floorDetails: "Multiple Floor Options",
    parkingSpaces: 3,
    suitableFor: ["Small to Large Office", "Showroom", "Retail Space", "Business Center"],
    companyLogo: "/placeholder.svg?height=60&width=120",
    description:
      "Nakshatra Regalia 2 by Nakshatra Group offers flexible commercial spaces ranging from compact offices to large showrooms. Perfect for businesses of all sizes with premium amenities and strategic location.",
    amenities: [
      "High Speed Internet",
      "24/7 Security",
      "Power Backup",
      "Parking",
      "Flexible Layouts",
      "Modern Infrastructure",
    ],
    gallery: [
      "/images/commercial/nakshatra-regalia-2.jpg",
      "/images/commercial/nakshatra-regalia-2-gallery-1.jpg",
      "/images/commercial/nakshatra-regalia-2-gallery-2.jpg",
    ],
    rera: "PR/GJ/GANDHINAGAR/GANDHINAGAR/GIFT Urban Development Authority/CAA14350/281024/311230",
  },
  {
    id: "c6",
    name: "The Identity",
    category: "commercial",
    type: "Office Spaces / Showrooms",
    developer: "Dobariya, Rashmi & Sangini Group",
    price: "₹68 Lac - ₹6 Cr",
    priceUnit: "",
    priceDescription: "Office & Showroom Options Available",
    officeSize: "801 – 1500 Sqft",
    showroomSize: "2800 – 3000 Sqft",
    officePrice: "₹68 Lac – ₹1.28 Cr",
    showroomPrice: "₹2.80 Cr – ₹6 Cr",
    image: "/images/commercial/the-identity.jpg",
    heroImage: "/images/commercial/the-identity.jpg",
    location: "Adani Shantigram",
    possession: "Dec 2027",
    size: "801 - 3000",
    superBuiltUpArea: "sqft (Office: 801-1500, Showroom: 2800-3000)",
    floorDetails: "Ground to Premium Floors",
    parkingSpaces: 2,
    suitableFor: ["Corporate Office", "Showroom", "Boutique Store", "Professional Services"],
    companyLogo: "/placeholder.svg?height=60&width=120",
    description:
      "The Identity by Dobariya, Rashmi & Sangini Group offers distinctive commercial spaces with unique architectural design. Ideal for businesses seeking a premium identity and professional presence.",
    amenities: [
      "High Speed Internet",
      "24/7 Security",
      "Power Backup",
      "Parking",
      "Modern Design",
      "Professional Lobby",
    ],
    gallery: [
      "/images/commercial/the-identity.jpg",
      "/images/commercial/the-identity-gallery-1.jpg",
      "/images/commercial/the-identity-gallery-2.jpg",
      "/images/commercial/the-identity-gallery-3.jpg",
      "/images/commercial/the-identity-gallery-4.jpg",
    ],
    rera: "PR/GJ/GANDHINAGAR/GANDHINAGAR/GIFT Urban Development Authority/CAA14504/121224/301230",
  },
  {
    id: "c7",
    name: "Yogi Siban",
    category: "commercial",
    type: "Showrooms",
    developer: "Yogi & Akshar & Globe & United Buildcon",
    price: "₹4.67 Cr - ₹6.05 Cr",
    priceUnit: "",
    priceDescription: "Premium Showroom Spaces",
    showroomSize: "1700 – 5500 Sqft",
    showroomPrice: "₹4.67 Cr – ₹6.05 Cr",
    image: "/images/commercial/yogi-siban.jpg",
    heroImage: "/images/commercial/yogi-siban.jpg",
    location: "Adani Shantigram",
    possession: "Dec 2030",
    size: "1700 - 5500",
    superBuiltUpArea: "sqft",
    floorDetails: "Ground Floor with High Visibility",
    parkingSpaces: 4,
    suitableFor: ["Large Showroom", "Retail Store", "Brand Outlet", "Display Center"],
    companyLogo: "/placeholder.svg?height=60&width=120",
    description:
      "Yogi Siban by Yogi & Akshar & Globe & United Buildcon offers premium showroom spaces with excellent visibility and accessibility. Perfect for retail businesses, brand outlets, and large display centers with flexible sizing options.",
    amenities: [
      "High Visibility",
      "24/7 Security",
      "Power Backup",
      "Ample Parking",
      "Loading Area",
      "Customer Facilities",
    ],
    gallery: [
      "/images/commercial/yogi-siban.jpg",
      "/images/commercial/yogi-siban-gallery-1.jpg",
      "/images/commercial/yogi-siban-gallery-2.jpg",
      "/images/commercial/yogi-siban-gallery-3.jpg",
      "/images/commercial/yogi-siban-gallery-4.jpg",
    ],
    rera: "PR/GJ/GANDHINAGAR/GANDHINAGAR/GIFT Urban Development Authority/MAA14625/311224/311230",
  },
]

export async function getPropertiesByCategory(category: "residential" | "commercial"): Promise<Property[]> {
  try {
    await new Promise((resolve) => setTimeout(resolve, 100))
    return properties.filter((property) => property.category === category)
  } catch (error) {
    console.error("Error fetching properties by category:", error)
    throw new Error("Failed to fetch properties by category")
  }
}

export async function getProperties(): Promise<Property[]> {
  try {
    await new Promise((resolve) => setTimeout(resolve, 100))
    return properties
  } catch (error) {
    console.error("Error fetching properties:", error)
    throw new Error("Failed to fetch properties")
  }
}

export async function getPropertyById(id: string): Promise<Property | null> {
  try {
    await new Promise((resolve) => setTimeout(resolve, 100))
    const property = properties.find((property) => property.id === id)
    return property || null
  } catch (error) {
    console.error("Error fetching property:", error)
    throw new Error("Failed to fetch property")
  }
}
